services:
  mysql:
    image: mysql:latest
    container_name: mysql_microservice_nest_app
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
      MYSQL_USER: devteam
      MYSQL_PASSWORD: soksan
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
